[workspace]
authors = ["Nick Ulle <nick.ulle@gmail.com>"]
channels = ["conda-forge"]
name = "2025_duckdb"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"
jupyter = ">=1.1.1,<2"
pandas = ">=2.3.3,<3"
polars = ">=1.34.0,<2"
python-duckdb = ">=1.4.1,<2"
pyarrow = ">=21.0.0,<22"

[target.unix.dependencies]
duckdb-cli = ">=1.3.2,<2"
